# Generated by Django 5.0.3 on 2024-04-11 11:56

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=80, verbose_name='First Name')),
                ('name_last', models.CharField(max_length=100, verbose_name='Last Name')),
                ('headshot', versatileimagefield.fields.VersatileImageField(upload_to='headshots/', verbose_name='Headshot')),
                ('headshot_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Аватар пользователя',
                'verbose_name_plural': 'Аватары пользователей',
            },
        ),
    ]
